### ISSUE TITLE
Doesn't start any more with error: Could not activate remote peer 'net.openvpn.v3.configuration': unit failed

### ISSUE THREAD

**Issue by sajonCC** [OpenVPN/openvpn3-indicator#23]
After system update, openvpn3-indicator doesn't start any more. When launching from CLI this is an error.
``` openvpn3-indicator -d

(openvpn3-indicator:6616): Gtk-WARNING **: 10:07:16.861: Theme parsing error: gtk-dark.css:1710:67: Junk at end of value for background-image

(openvpn3-indicator:6616): Gtk-WARNING **: 10:07:16.861: Theme parsing error: gtk-dark.css:2822:2: Expected semicolon

(openvpn3-indicator:6616): Gtk-WARNING **: 10:07:16.862: Theme parsing error: gtk-dark.css:4591:34: Expected a valid selector
INFO:root:Startup
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/openvpn3-indicator/openvpn3_indicator/application.py", line 119, in on_startup
  File "/usr/lib/python3.11/site-packages/openvpn3/ConfigManager.py", line 271, in __init__
    self.__manager_object = dbuscon.get_object('net.openvpn.v3.configuration',
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: Could not activate remote peer 'net.openvpn.v3.configuration': unit failed
INFO:root:Activate
```

I'm on OpenSuse Tumbleweed Slowroll 

python version:

> Python 3.11.10 (main, Sep 09 2024, 17:03:08) [GCC] on linux
> Type "help", "copyright", "credits" or "license" for more information.

**Comment by sajonCC** [comment]
This was not a problem with openvpn3-indicator. The problem was with openvpn3 itself. Problem solved.
